############################# Makefile ##########################
compile: 
	gcc -o algorithms_sort algorithms_sort.c
clean: 
	rm -rf algorithms_sort
exec:
	#./alrogithms_sort 3 6 4 8 0 1 10 22 13 45 23 21
	./algorithms_sort num.1000.1.in