############################# Makefile ##########################
compile: 
	gcc -o algorithms_sort algorithms_sort.c
clean: 
	rm -rf algorithms_sort
exec:
	./exec 3 44 87 71 20 33 2 24 55 16 07 98 79 80
	#./algorithms_sort num.1000.1.in