############################# Makefile ##########################
compile: 
	gcc -o alrogithms_sort alrogithms_sort.c
clean: 
	rm -rf alrogithms_sort
exec:
	#./alrogithms_sort 3 6 4 8 0 1 10 22 13 45 23 21
	./alrogithms_sort num.1000.1.in