############################# Makefile ##########################
compile: 
	g++ -o algorithms_sort algorithms_sort.c
clean: 
	rm -rf algorithms_sort
exec:
	./algorithms_sort 16 4 10 14 7 9 3 2 8 1
	#./algorithms_sort num.1000.1.in